-- MySQL Script generated by MySQL Workbench
-- dom 14 oct 2018 21:27:26 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdsoccer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdsoccer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdsoccer` DEFAULT CHARACTER SET utf8 ;
USE `bdsoccer` ;

-- -----------------------------------------------------
-- Table `bdsoccer`.`Continentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`Continentes` (
  `idContinente` INT NOT NULL AUTO_INCREMENT,
  `nombreContinente` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idContinente`),
  UNIQUE INDEX `idContinente_UNIQUE` (`idContinente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`Paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`Paises` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `nombrePais` VARCHAR(45) NOT NULL,
  `idContinente` INT NOT NULL,
  PRIMARY KEY (`idPais`),
  INDEX `fk_Paises_idContinente_idx` (`idContinente` ASC),
  CONSTRAINT `fk_Paises_idContinente`
    FOREIGN KEY (`idContinente`)
    REFERENCES `bdsoccer`.`Continentes` (`idContinente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`Confederaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`Confederaciones` (
  `idConfederacion` INT NOT NULL AUTO_INCREMENT,
  `idContinente` INT NOT NULL,
  `nombreConfederacion` VARCHAR(45) NOT NULL,
  `fundacionConfederacion` DATE NOT NULL,
  `sedeConfederacion` VARCHAR(45) NULL,
  `idPais` INT NOT NULL,
  `imagenConfederacion` LONGBLOB NULL,
  PRIMARY KEY (`idConfederacion`),
  UNIQUE INDEX `idConfederacion_UNIQUE` (`idConfederacion` ASC),
  INDEX `fk_Confederacion_idContinente_idx` (`idContinente` ASC),
  INDEX `fk_Confederacion_idPais_idx` (`idPais` ASC),
  CONSTRAINT `fk_Confederacion_idContinente`
    FOREIGN KEY (`idContinente`)
    REFERENCES `bdsoccer`.`Continentes` (`idContinente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Confederacion_idPais`
    FOREIGN KEY (`idPais`)
    REFERENCES `bdsoccer`.`Paises` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`Federaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`Federaciones` (
  `idFederacion` INT NOT NULL AUTO_INCREMENT,
  `idConfederacion` INT NOT NULL,
  `nombreFederacion` VARCHAR(45) NOT NULL,
  `fundacionFederacion` DATE NOT NULL,
  `sedeFederacion` VARCHAR(45) NULL,
  `idPais` INT NOT NULL,
  `imagenFederacion` LONGBLOB NULL,
  PRIMARY KEY (`idFederacion`),
  UNIQUE INDEX `idConfederacion_UNIQUE` (`idConfederacion` ASC),
  UNIQUE INDEX `idPais_UNIQUE` (`idPais` ASC),
  CONSTRAINT `fk_Federacion_idConfederacion`
    FOREIGN KEY (`idConfederacion`)
    REFERENCES `bdsoccer`.`Confederaciones` (`idConfederacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Federacion_idPais`
    FOREIGN KEY (`idPais`)
    REFERENCES `bdsoccer`.`Paises` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`Asociaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`Asociaciones` (
  `idAsociacion` INT NOT NULL AUTO_INCREMENT,
  `idFederacion` INT NOT NULL,
  `nombreAsociacion` VARCHAR(45) NOT NULL,
  `fundacionAsociacion` DATE NOT NULL,
  `sedeAsociacion` VARCHAR(45) NOT NULL,
  `idPais` INT NOT NULL,
  `imagenAsociacion` LONGBLOB NULL,
  PRIMARY KEY (`idAsociacion`),
  INDEX `fk_Asociacion_idFederacion_idx` (`idFederacion` ASC),
  INDEX `fk_Asociacion_idPais_idx` (`idPais` ASC),
  CONSTRAINT `fk_Asociacion_idFederacion`
    FOREIGN KEY (`idFederacion`)
    REFERENCES `bdsoccer`.`Federaciones` (`idFederacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asociacion_idPais`
    FOREIGN KEY (`idPais`)
    REFERENCES `bdsoccer`.`Paises` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`Ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`Ciudades` (
  `idCiudad` INT NOT NULL AUTO_INCREMENT COMMENT '	',
  `nombreCiudad` VARCHAR(45) NOT NULL,
  `idPais` INT NOT NULL,
  PRIMARY KEY (`idCiudad`),
  INDEX `fk_Ciudad_idPais_idx` (`idPais` ASC),
  CONSTRAINT `fk_Ciudad_idPais`
    FOREIGN KEY (`idPais`)
    REFERENCES `bdsoccer`.`Paises` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`DirectoresTecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`DirectoresTecnicos` (
  `idDirectorTecnico` INT NOT NULL AUTO_INCREMENT,
  `nombreDirectorTecnico` VARCHAR(45) NOT NULL,
  `apellidosDirectorTecnico` VARCHAR(45) NOT NULL,
  `nacimientoDirectorTecnico` DATE NULL,
  `edadDirectorTecnico` INT NULL,
  `idPais` INT NOT NULL,
  `imagenDirectorTecnico` LONGBLOB NULL,
  PRIMARY KEY (`idDirectorTecnico`),
  INDEX `fk_Director Tecnico_idPais_idx` (`idPais` ASC),
  CONSTRAINT `fk_Director Tecnico_idPais`
    FOREIGN KEY (`idPais`)
    REFERENCES `bdsoccer`.`Paises` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`Estadios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`Estadios` (
  `idEstadio` INT NOT NULL AUTO_INCREMENT,
  `nombreEstadio` VARCHAR(45) NOT NULL,
  `idPais` INT NOT NULL,
  `idCiudad` INT NOT NULL,
  `inauguracionEstadio` DATE NULL,
  `capacidadEstadio` INT NULL,
  PRIMARY KEY (`idEstadio`),
  INDEX `fk_Estadio_idCiudad_idx` (`idCiudad` ASC),
  INDEX `fk_Estadio_idPais_idx` (`idPais` ASC),
  CONSTRAINT `fk_Estadio_idPais`
    FOREIGN KEY (`idPais`)
    REFERENCES `bdsoccer`.`Paises` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estadio_idCiudad`
    FOREIGN KEY (`idCiudad`)
    REFERENCES `bdsoccer`.`Ciudades` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`Clubes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`Clubes` (
  `idClub` INT NOT NULL AUTO_INCREMENT,
  `nombreClub` VARCHAR(45) NOT NULL,
  `imagenClub` LONGBLOB NOT NULL,
  `fundacionClub` DATE NOT NULL,
  `sedeClub` VARCHAR(45) NULL,
  `idCiudad` INT NOT NULL,
  `idPais` INT NOT NULL,
  `correoClub` VARCHAR(45) NULL,
  `telefonoClub` INT NULL,
  `idAsociacion` INT NOT NULL,
  `idDirectorTecnico` INT NOT NULL,
  `idEstadio` INT NULL,
  PRIMARY KEY (`idClub`),
  INDEX `fk_Club_idAsociacion_idx` (`idAsociacion` ASC),
  INDEX `fk_Club_idDirectorTecnico_idx` (`idDirectorTecnico` ASC),
  INDEX `fk_Club_idEstadio_idx` (`idEstadio` ASC),
  INDEX `fk_Club_idCiudad_idx` (`idCiudad` ASC),
  INDEX `fk_Club_idPais_idx` (`idPais` ASC),
  CONSTRAINT `fk_Club_idCiudad`
    FOREIGN KEY (`idCiudad`)
    REFERENCES `bdsoccer`.`Ciudades` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Club_idPais`
    FOREIGN KEY (`idPais`)
    REFERENCES `bdsoccer`.`Paises` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Club_idAsociacion`
    FOREIGN KEY (`idAsociacion`)
    REFERENCES `bdsoccer`.`Asociaciones` (`idAsociacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Club_idDirectorTecnico`
    FOREIGN KEY (`idDirectorTecnico`)
    REFERENCES `bdsoccer`.`DirectoresTecnicos` (`idDirectorTecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Club_idEstadio`
    FOREIGN KEY (`idEstadio`)
    REFERENCES `bdsoccer`.`Estadios` (`idEstadio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`Torneos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`Torneos` (
  `idTorneo` INT NOT NULL AUTO_INCREMENT,
  `nombreTorneo` VARCHAR(45) NOT NULL,
  `edicion` INT NOT NULL,
  `idConfederacion` INT NULL,
  `idAsociacion` INT NULL,
  `idClubCampeon` INT NULL,
  PRIMARY KEY (`idTorneo`),
  UNIQUE INDEX `idTorneoConfederacion_UNIQUE` (`idTorneo` ASC),
  INDEX `fk_Torneo_idConfederacion_idx` (`idConfederacion` ASC),
  INDEX `fk_Torneo_idAsociacion_idx` (`idAsociacion` ASC),
  INDEX `fk_Torneos_idClubCampeon_idx` (`idClubCampeon` ASC),
  CONSTRAINT `fk_Torneo_idConfederacion`
    FOREIGN KEY (`idConfederacion`)
    REFERENCES `bdsoccer`.`Confederaciones` (`idConfederacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Torneo_idAsociacion`
    FOREIGN KEY (`idAsociacion`)
    REFERENCES `bdsoccer`.`Asociaciones` (`idAsociacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Torneos_idClubCampeon`
    FOREIGN KEY (`idClubCampeon`)
    REFERENCES `bdsoccer`.`Clubes` (`idClub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`Jugadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`Jugadores` (
  `idJugador` INT NOT NULL AUTO_INCREMENT,
  `nombreJugador` VARCHAR(45) NOT NULL,
  `apellidosJugador` VARCHAR(45) NOT NULL,
  `nacimientoJugador` DATE NOT NULL,
  `edadJugador` INT NOT NULL,
  `posicionJugador` VARCHAR(45) NOT NULL,
  `alturaJugador` INT NULL,
  `pesoJugador` INT NULL,
  `pieJugador` VARCHAR(45) NULL,
  `idClub` INT NULL,
  `golesJugador` INT NULL,
  `amarillasJugador` INT NULL,
  `rojasJugador` INT NULL,
  `minutostotalesJugador` INT NULL,
  `imagenJugador` LONGBLOB NULL,
  `idPais` INT NOT NULL,
  PRIMARY KEY (`idJugador`),
  INDEX `fk_Jugador_idClub_idx` (`idClub` ASC),
  INDEX `fk_Jugadores_idPais_idx` (`idPais` ASC),
  CONSTRAINT `fk_Jugador_idClub`
    FOREIGN KEY (`idClub`)
    REFERENCES `bdsoccer`.`Clubes` (`idClub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jugadores_idPais`
    FOREIGN KEY (`idPais`)
    REFERENCES `bdsoccer`.`Paises` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`Arbitros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`Arbitros` (
  `idArbitro` INT NOT NULL AUTO_INCREMENT,
  `nombreArbitro` VARCHAR(45) NOT NULL,
  `apellidosArbitro` VARCHAR(45) NOT NULL,
  `tipoArbitro` VARCHAR(45) NOT NULL,
  `nacimientoArbitro` DATE NULL,
  `idPais` INT NOT NULL,
  `edadArbitro` INT NULL,
  `idAsociacion` INT NOT NULL,
  `gradoArbitro` VARCHAR(45) NOT NULL,
  `imagenArbitro` LONGBLOB NULL,
  PRIMARY KEY (`idArbitro`),
  INDEX `fk_Arbitro_idAsociacion_idx` (`idAsociacion` ASC),
  INDEX `fk_Arbitros_idPais_idx` (`idPais` ASC),
  CONSTRAINT `fk_Arbitro_idAsociacion`
    FOREIGN KEY (`idAsociacion`)
    REFERENCES `bdsoccer`.`Asociaciones` (`idAsociacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Arbitros_idPais`
    FOREIGN KEY (`idPais`)
    REFERENCES `bdsoccer`.`Paises` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`Partidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`Partidos` (
  `idPartido` INT NOT NULL AUTO_INCREMENT,
  `clubLocalPartido` INT NOT NULL,
  `clubVisitaPartido` INT NOT NULL,
  `fechaPartido` DATETIME NOT NULL,
  `jornadaPartido` VARCHAR(45) NOT NULL,
  `idEstadio` INT NOT NULL,
  `idArbitroCentral` INT NOT NULL COMMENT '	',
  `idTorneo` INT NOT NULL,
  `TipoPartido` VARCHAR(45) NOT NULL,
  `golesVisitaPartido` INT NOT NULL,
  `golesLocalPartido` INT NOT NULL,
  `estadoPartido` VARCHAR(45) NULL,
  `idArbitroAsistente1` INT NOT NULL,
  `idArbitroAsistente2` INT NOT NULL,
  `idCuartoArbitro` INT NULL,
  PRIMARY KEY (`idPartido`),
  INDEX `fk_Partido_idArbitro_idx` (`idArbitroCentral` ASC),
  INDEX `fk_Partido_idTorneo_idx` (`idTorneo` ASC),
  INDEX `fk_Partido_clubLocalPartido_idx` (`clubLocalPartido` ASC),
  INDEX `fk_Partido_clubVisitaPartido_idx` (`clubVisitaPartido` ASC),
  INDEX `fk_Partido_idEstadio_idx` (`idEstadio` ASC),
  INDEX `fk_Partidos_idArbitroAsistente1_idx` (`idArbitroAsistente1` ASC),
  INDEX `fk_Partidos_idArbitroAsistente2_idx` (`idArbitroAsistente2` ASC),
  INDEX `fk_Partidos_idCuartoArbitro_idx` (`idCuartoArbitro` ASC),
  CONSTRAINT `fk_Partido_idEstadio`
    FOREIGN KEY (`idEstadio`)
    REFERENCES `bdsoccer`.`Estadios` (`idEstadio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_idArbitroCentral`
    FOREIGN KEY (`idArbitroCentral`)
    REFERENCES `bdsoccer`.`Arbitros` (`idArbitro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_idTorneo`
    FOREIGN KEY (`idTorneo`)
    REFERENCES `bdsoccer`.`Torneos` (`idTorneo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_clubLocalPartido`
    FOREIGN KEY (`clubLocalPartido`)
    REFERENCES `bdsoccer`.`Clubes` (`idClub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_clubVisitaPartido`
    FOREIGN KEY (`clubVisitaPartido`)
    REFERENCES `bdsoccer`.`Clubes` (`idClub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partidos_idArbitroAsistente1`
    FOREIGN KEY (`idArbitroAsistente1`)
    REFERENCES `bdsoccer`.`Arbitros` (`idArbitro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partidos_idArbitroAsistente2`
    FOREIGN KEY (`idArbitroAsistente2`)
    REFERENCES `bdsoccer`.`Arbitros` (`idArbitro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partidos_idCuartoArbitro`
    FOREIGN KEY (`idCuartoArbitro`)
    REFERENCES `bdsoccer`.`Arbitros` (`idArbitro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`TrayectoriasJugadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`TrayectoriasJugadores` (
  `idJugador` INT NOT NULL,
  `idClub` INT NOT NULL,
  `idTorneo` INT NOT NULL COMMENT '	',
  `camisetaJugador` INT NULL,
  PRIMARY KEY (`idJugador`, `idClub`, `idTorneo`),
  INDEX `fk_Trayectoria Jugador_idClub_idx` (`idClub` ASC),
  INDEX `fk_TrayectoriaJugador_idTorneo_idx` (`idTorneo` ASC),
  CONSTRAINT `fk_TrayectoriaJugador_idJugador`
    FOREIGN KEY (`idJugador`)
    REFERENCES `bdsoccer`.`Jugadores` (`idJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trayectoria Jugador_idClub`
    FOREIGN KEY (`idClub`)
    REFERENCES `bdsoccer`.`Clubes` (`idClub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TrayectoriaJugador_idTorneo`
    FOREIGN KEY (`idTorneo`)
    REFERENCES `bdsoccer`.`Torneos` (`idTorneo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`TrayectoriasDirectoresTecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`TrayectoriasDirectoresTecnicos` (
  `idDirectorTecnico` INT NOT NULL,
  `idClub` INT NOT NULL,
  PRIMARY KEY (`idDirectorTecnico`, `idClub`),
  INDEX `fk_Trayectoria Director Tecnico_idClub_idx` (`idClub` ASC),
  CONSTRAINT `fk_Trayectoria Director Tecnico_idDirectorTecnico`
    FOREIGN KEY (`idDirectorTecnico`)
    REFERENCES `bdsoccer`.`DirectoresTecnicos` (`idDirectorTecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trayectoria Director Tecnico_idClub`
    FOREIGN KEY (`idClub`)
    REFERENCES `bdsoccer`.`Clubes` (`idClub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`Historiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`Historiales` (
  `idPartido` INT NOT NULL,
  `idJugador` INT NOT NULL,
  `golJugador` INT NULL,
  `amarillaJugador` INT NULL,
  `rojaJugador` INT NULL,
  `minutosJugador` INT NULL,
  PRIMARY KEY (`idPartido`, `idJugador`),
  UNIQUE INDEX `idJugador_UNIQUE` (`idJugador` ASC),
  UNIQUE INDEX `idPartido_UNIQUE` (`idPartido` ASC),
  CONSTRAINT `fk_Historial_idPartido`
    FOREIGN KEY (`idPartido`)
    REFERENCES `bdsoccer`.`Partidos` (`idPartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historial_idJugador`
    FOREIGN KEY (`idJugador`)
    REFERENCES `bdsoccer`.`Jugadores` (`idJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsoccer`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsoccer`.`users` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `remember_token` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
